In [1]:
import cv2

In [15]:
im_g=cv2.imread("smallgray.png",0) # im_g means image gray , the 0 after file name means a gray image ,if that is a 1 that means a rgb file.

In [3]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
#actually white is 255 ;

In [8]:
# if we want to get a rgb picture ,it would be a 3- dimension array in open cv
im_g=cv2.imread("smallgray.png",1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
# create images in cv2 
cv2.imwrite("newsmallgray.png",im_g)

True

In [11]:
a=[1,2,3]

In [12]:
a[0:1]

[1]

In [13]:
a[1:3]

[2, 3]

In [16]:
# slice cv2 object
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [17]:
# slice cv2 object
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [19]:
# see the shape of our numpy array 
im_g.shape

(3, 5)

In [20]:
# indexing
# indexing a numpy array
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [21]:
# indexing
# indexing a numpy array
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [22]:
# indexing
# indexing a numpy array
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
